"""Integration tests for 'publish zenodo prepare/upload/check-readiness/release'.

These only exercise validation and --dry-run paths. Nothing here calls the
real Zenodo API — dry-run returns before any network call in
donadataset.services.zenodo, and the pure-validation checks in
resolve_zenodo_record_id() run before any download attempt.

There is no --config flag: every command derives its resolved config path
from --repo-id/--output-dir/--hfh-output-dir (rendering the single bundled
templates/Zenodo.yaml.j2). token_env_var is fixed to ZENODO_TOKEN in that
template (not a settings.toml field or a flag), so these tests monkeypatch
ZENODO_TOKEN directly. Files like zenodo_linked_dataset_record.json and
public_release_readiness_report.json always live at fixed names inside
--output-dir (zenodo.output.*_filename isn't a flag either), so tests place
hand-written JSON there directly instead of pointing a custom YAML at an
arbitrary path.
"""
import json
from pathlib import Path

import pytest
import yaml
from typer.testing import CliRunner

from donadataset.main import app
from donadataset.services import zenodo as zenodo_service

runner = CliRunner()

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ZENODO_JINJA_TEMPLATE_PATH = REPO_ROOT / "templates" / "Zenodo.yaml.j2"


def _generate_prepare_and_fake_download(
    tmp_path: Path, example_source_dataset: Path, repo_id: str = "myuser/donadataset-test",
) -> tuple[Path, Path]:
    """generate real -> huggingface prepare -> a hand-written 'passed'
    verification_report_downloaded.json placed where 'zenodo prepare' itself
    would write it (we don't call the real HuggingFace Hub download here).
    Returns (hf_output_dir, zenodo_output_dir).
    """
    real_output = tmp_path / "real"
    real_result = runner.invoke(app, [
        "generate", "real", "--source", str(example_source_dataset), "--output", str(real_output),
    ])
    assert real_result.exit_code == 0, real_result.output

    hf_output_dir = tmp_path / "HFH"
    prepare_result = runner.invoke(app, [
        "publish", "huggingface", "prepare",
        "--source-dataset-dir", str(real_output),
        "--output-dir", str(hf_output_dir),
        "--repo-id", repo_id,
    ])
    assert prepare_result.exit_code == 0, prepare_result.output

    zenodo_output_dir = tmp_path / "Zenodo"
    downloaded_report_path = zenodo_output_dir / "verification_report_downloaded.json"
    downloaded_report_path.parent.mkdir(parents=True, exist_ok=True)
    downloaded_report_path.write_text(json.dumps({
        "status": "passed", "repo_id": repo_id, "repo_type": "dataset",
        "global_files_verified": 5, "internal_tar_members_verified": 3, "num_errors": 0,
    }))

    return hf_output_dir, zenodo_output_dir


# ── prepare ───────────────────────────────────────────────────────────────────

def test_prepare_requires_zenodo_enabled(tmp_path: Path):
    """zenodo.enabled is always true in the bundled template (no CLI flag
    for it) — exercise the service-layer guard directly instead."""
    config_path = tmp_path / "custom.yaml"
    config_path.write_text(yaml.safe_dump({"zenodo": {"enabled": False}}))

    with pytest.raises(RuntimeError, match="zenodo.enabled"):
        zenodo_service.run_zenodo_linked_dataset_creation(config_path, dry_run=True)


def test_prepare_dry_run_succeeds_with_valid_evidence(tmp_path: Path, example_source_dataset: Path):
    _, zenodo_output_dir = _generate_prepare_and_fake_download(tmp_path, example_source_dataset)

    result = runner.invoke(app, [
        "publish", "zenodo", "prepare",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir), "--dry-run",
    ])

    assert result.exit_code == 0, result.output
    assert "Dry run enabled" in result.output


def test_prepare_dry_run_does_not_depend_on_any_local_hfh_export(tmp_path: Path):
    """Evidence files are fetched from a live HuggingFace Hub download — so
    --dry-run must succeed even without ever having run 'huggingface
    prepare' at all."""
    result = runner.invoke(app, [
        "publish", "zenodo", "prepare",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(tmp_path / "Zenodo"), "--dry-run",
    ])

    assert result.exit_code == 0, result.output
    assert "will not be downloaded" in result.output.lower()


def test_prepare_dry_run_does_not_require_a_pre_existing_downloaded_report(
    tmp_path: Path, example_source_dataset: Path,
):
    """The downloaded verification report is only generated by a live
    HuggingFace Hub download, which --dry-run deliberately skips (no network
    calls) — so its absence must not fail a dry run."""
    _, zenodo_output_dir = _generate_prepare_and_fake_download(tmp_path, example_source_dataset)
    (zenodo_output_dir / "verification_report_downloaded.json").unlink()

    result = runner.invoke(app, [
        "publish", "zenodo", "prepare",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir), "--dry-run",
    ])

    assert result.exit_code == 0, result.output
    assert "will not be downloaded" in result.output.lower()


# ── templates/Zenodo.yaml.j2 (Jinja2 template rendered by 'zenodo prepare') ──

def test_prepare_renders_jinja_template_using_only_repo_id_and_output_dir(tmp_path: Path):
    """Only --repo-id and --output-dir (Zenodo's own directory) should be
    needed to get a working render — no local HuggingFace export required at
    all, since evidence files come from a live download. Everything else
    (title, description, license, author, the HuggingFace related-identifier
    URLs) comes from settings.toml defaults."""
    result = runner.invoke(app, [
        "publish", "zenodo", "prepare",
        "--output-dir", str(tmp_path / "Zenodo_jinja-zenodo-demo"),
        "--repo-id", "myuser/jinja-zenodo-demo",
        "--dry-run",
    ])

    assert result.exit_code == 0, result.output
    assert "Dry run enabled" in result.output


def test_prepare_jinja_template_keeps_placeholder_when_repo_id_missing(tmp_path: Path):
    """Without --repo-id (and no settings.toml default in the isolated test
    HOME), the rendered related_identifiers must stay an obvious placeholder
    instead of silently producing a broken URL."""
    from donadataset.services.zenodo import build_zenodo_template_context, load_config_source

    ctx = build_zenodo_template_context(
        hfh_output_dir=str(tmp_path / "HFH"), zenodo_output_dir=str(tmp_path / "Zenodo"), repo_id=None,
    )
    config = load_config_source(ZENODO_JINJA_TEMPLATE_PATH, **ctx)

    assert "REPLACE_WITH_HF_USER" in config["huggingface"]["repo_id"]
    assert "REPLACE_WITH_HF_USER" in config["zenodo"]["related_identifiers"]["huggingface_dataset_url"]


def test_prepare_sync_existing_draft_requires_linked_record(tmp_path: Path, example_source_dataset: Path):
    _, zenodo_output_dir = _generate_prepare_and_fake_download(tmp_path, example_source_dataset)

    result = runner.invoke(app, [
        "publish", "zenodo", "prepare",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
        "--dry-run", "--sync-existing-draft",
    ])

    assert result.exit_code == 1
    assert "linked dataset record not found" in result.output.lower()


# ── upload (metadata update) ──────────────────────────────────────────────────

def test_upload_dry_run_succeeds_with_valid_linked_record(tmp_path: Path, example_source_dataset: Path):
    hf_output_dir, zenodo_output_dir = _generate_prepare_and_fake_download(tmp_path, example_source_dataset)

    linked_record_path = zenodo_output_dir / "zenodo_linked_dataset_record.json"
    linked_record_path.write_text(json.dumps({
        "zenodo_environment": "sandbox",
        "deposition_id": 12345,
        "record_id": 12345,
        "reserved_doi": "10.5072/zenodo.12345",
        "doi_url": "https://doi.org/10.5072/zenodo.12345",
        "record_url": "https://sandbox.zenodo.org/records/12345",
    }))

    result = runner.invoke(app, [
        "publish", "zenodo", "upload",
        "--repo-id", "myuser/donadataset-test",
        "--hfh-output-dir", str(hf_output_dir),
        "--output-dir", str(zenodo_output_dir),
        "--dry-run",
    ])

    assert result.exit_code == 0, result.output
    assert "Dry run enabled" in result.output
    # dry-run must not touch any file
    assert not (hf_output_dir / "README.md.bak").exists()


def test_upload_fails_when_linked_record_missing(tmp_path: Path, example_source_dataset: Path):
    hf_output_dir, zenodo_output_dir = _generate_prepare_and_fake_download(tmp_path, example_source_dataset)

    result = runner.invoke(app, [
        "publish", "zenodo", "upload",
        "--repo-id", "myuser/donadataset-test",
        "--hfh-output-dir", str(hf_output_dir),
        "--output-dir", str(zenodo_output_dir),
        "--dry-run",
    ])

    assert result.exit_code == 1
    assert "not found" in result.output.lower()


# ── download ──────────────────────────────────────────────────────────────────

def test_download_requires_deploy_dir(tmp_path: Path):
    result = runner.invoke(app, ["publish", "zenodo", "download", "--zenodo-record", "12345"])
    assert result.exit_code != 0


def test_download_rejects_both_record_and_doi(tmp_path: Path):
    result = runner.invoke(app, [
        "publish", "zenodo", "download",
        "--deploy-dir", str(tmp_path / "deploy"),
        "--zenodo-record", "12345",
        "--doi", "10.5072/zenodo.12345",
    ])
    assert result.exit_code == 1
    assert "only one of" in result.output.lower()


def test_download_requires_record_or_doi(tmp_path: Path):
    result = runner.invoke(app, ["publish", "zenodo", "download", "--deploy-dir", str(tmp_path / "deploy")])
    assert result.exit_code == 1
    assert "must provide" in result.output.lower()


def test_download_rejects_unresolvable_identifier(tmp_path: Path):
    result = runner.invoke(app, [
        "publish", "zenodo", "download",
        "--deploy-dir", str(tmp_path / "deploy"),
        "--zenodo-record", "not-a-valid-id",
    ])
    assert result.exit_code == 1
    assert "could not resolve" in result.output.lower()


# ── check-readiness ────────────────────────────────────────────────────────────
#
# verify_hfh_public_urls() always makes a real HTTP request (regardless of
# token), so only the validation that happens before it — repo_id/
# environment/linked-record checks — can be tested hermetically here.

def test_check_readiness_rejects_invalid_repo_id(tmp_path: Path):
    result = runner.invoke(app, [
        "publish", "zenodo", "check-readiness",
        "--repo-id", "no-slash-here", "--output-dir", str(tmp_path / "Zenodo"),
    ])

    assert result.exit_code == 1
    assert "repo_id" in result.output


def test_check_readiness_rejects_invalid_zenodo_environment(tmp_path: Path):
    """--environment is a typed choice (sandbox/production) — an invalid
    value is now rejected by Typer itself, before any of our own code runs."""
    result = runner.invoke(app, [
        "publish", "zenodo", "check-readiness",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(tmp_path / "Zenodo"),
        "--environment", "bogus",
    ])

    assert result.exit_code != 0
    assert "not one of" in result.output.lower()


def test_check_readiness_fails_when_linked_record_missing(tmp_path: Path):
    result = runner.invoke(app, [
        "publish", "zenodo", "check-readiness",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(tmp_path / "Zenodo"),
    ])

    assert result.exit_code == 1
    assert "linked dataset record not found" in result.output.lower()


def test_check_readiness_fails_on_malformed_linked_record(tmp_path: Path):
    zenodo_output_dir = tmp_path / "Zenodo"
    zenodo_output_dir.mkdir(parents=True)
    # zenodo_environment present, but reserved_doi missing -> should fail on that check
    (zenodo_output_dir / "zenodo_linked_dataset_record.json").write_text(
        json.dumps({"deposition_id": 123, "zenodo_environment": "sandbox"}),
    )

    result = runner.invoke(app, [
        "publish", "zenodo", "check-readiness",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1
    assert "reserved_doi" in result.output


# ── release ───────────────────────────────────────────────────────────────────
#
# run_release() only touches the network *after* validate_readiness_report()
# and get_zenodo_token(), so only the checks up to (and including) those are
# testable hermetically here.

VALID_LINKED_RECORD = {
    "deposition_id": 12345,
    "record_id": 12345,
    "reserved_doi": "10.5072/zenodo.12345",
    "doi_url": "https://doi.org/10.5072/zenodo.12345",
    "record_url": "https://sandbox.zenodo.org/records/12345",
    "zenodo_environment": "sandbox",
}


def _write_release_files(zenodo_output_dir: Path, linked_record: dict, readiness_report: dict | None) -> None:
    zenodo_output_dir.mkdir(parents=True, exist_ok=True)
    (zenodo_output_dir / "zenodo_linked_dataset_record.json").write_text(json.dumps(linked_record))
    if readiness_report is not None:
        (zenodo_output_dir / "public_release_readiness_report.json").write_text(json.dumps(readiness_report))


def test_release_fails_when_linked_record_missing(tmp_path: Path):
    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(tmp_path / "Zenodo"),
    ])

    assert result.exit_code == 1
    assert "linked dataset record not found" in result.output.lower()


def test_release_fails_on_malformed_linked_record(tmp_path: Path):
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(zenodo_output_dir, {"deposition_id": 123}, readiness_report=None)

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1


def test_release_requires_readiness_report_by_default(tmp_path: Path):
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(zenodo_output_dir, VALID_LINKED_RECORD, readiness_report=None)

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1
    assert "readiness report not found" in result.output.lower()


def test_release_fails_when_readiness_report_has_errors(tmp_path: Path):
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(
        zenodo_output_dir, VALID_LINKED_RECORD,
        readiness_report={"status": "failed", "errors": ["hfh_public_urls: boom"]},
    )

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1
    assert "contains errors" in result.output.lower()


def test_release_fails_when_readiness_report_not_ready(tmp_path: Path):
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(
        zenodo_output_dir, VALID_LINKED_RECORD, readiness_report={"status": "failed", "errors": []},
    )

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1
    assert "does not indicate a passed" in result.output.lower()


def test_release_missing_token_env_var_fails_after_readiness_passes(tmp_path: Path, monkeypatch):
    monkeypatch.delenv("ZENODO_TOKEN", raising=False)
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(
        zenodo_output_dir, VALID_LINKED_RECORD, readiness_report={"status": "passed", "errors": []},
    )

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
    ])

    assert result.exit_code == 1
    assert "ZENODO_TOKEN" in result.output


def test_release_skip_readiness_check_still_requires_token(tmp_path: Path, monkeypatch):
    """--skip-readiness-check bypasses the readiness gate, but the command
    must still reach (and fail cleanly on) the token check right after."""
    monkeypatch.delenv("ZENODO_TOKEN", raising=False)
    zenodo_output_dir = tmp_path / "Zenodo"
    _write_release_files(zenodo_output_dir, VALID_LINKED_RECORD, readiness_report=None)

    result = runner.invoke(app, [
        "publish", "zenodo", "release",
        "--repo-id", "myuser/donadataset-test", "--output-dir", str(zenodo_output_dir),
        "--skip-readiness-check",
    ])

    assert result.exit_code == 1
    assert "skipping public release readiness check" in result.output.lower()
    assert "ZENODO_TOKEN" in result.output
